Fixes to pyscaffold ($ putup --travis --tox --pre-commit mpl-tools)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,15 +14,13 @@ matrix:
     - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
 install:
   - source tests/travis_install.sh
-  - pip install -r requirements.txt
-  # ^  DEPRECATION WARNING:
-  # The automatic creation of a `requirements.txt` file is deprecated.
-  # See `Dependency Management` in the docs for other options.
 before_script:
-  - git config --global user.email "you@example.com"
-  - git config --global user.name "Your Name"
+  - git config --global user.email "patrick.n.raanes@gmail.com"
+  - git config --global user.name "Patrick N. Raanes"
 script:
   - python setup.py develop
+# - python setup.py test # DEPRECATED. USE WHAT'S BELOW INSTEAD
+# (requires that you did `$ putup --travis --tox --pre-commit`):
   - tox
   - |
     if [[ "$COVERAGE" == "true" ]]; then
@@ -30,7 +28,10 @@ script:
       pre-commit run --all-files
     fi
 after_success:
-  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
+  - |
+    if [[ "$COVERAGE" == "true" ]]; then
+       coveralls || echo "failed"
+    fi
 after_script:
   - travis-cleanup
 cache:
